### ISSUE TITLE
openssl missing

### ISSUE THREAD

**Issue by elalemanyo** [nohal/docker-signalk-server-node#1]
Hi,
I was trying to use your docker, but I get this error:

`Error: Could not find openssl on your system on this path: openssl`

So I copy your Dockerfile and add openssl on line 5:
`apk add ca-certificates git nodejs-lts wget sudo nodejs-npm openssl`

But now I get another error at the end:
`ERROR: Service 'web' failed to build: lstat signalk-server-node.sh: no such file or directory`

What I am doing wrong?

Thanks!

**Comment by nohal** [comment]
Fixed the openssl dependency, I have no idea what the other error means, is it all you get, no more info?

**Comment by elalemanyo** [comment]
That is what I see on the container logs:
```
No settings/defaults.json available
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
2017-06-09T08:04:53.372840510Z 
Error: EACCES: permission denied, open './settings/ssl-key.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at /var/signalk-server-node-master/lib/index.js:204:10
    at /var/signalk-server-node-master/node_modules/pem/lib/pem.js:370:16
    at /var/signalk-server-node-master/node_modules/pem/lib/pem.js:1079:20
    at /var/signalk-server-node-master/node_modules/pem/lib/pem.js:1046:9
    at done (/var/signalk-server-node-master/node_modules/pem/lib/pem.js:995:21)
    at ChildProcess.<anonymous> (/var/signalk-server-node-master/node_modules/pem/lib/pem.js:1010:13)
    at emitTwo (events.js:106:13)
```

Any idea?

Thanks!

**Comment by tkurki** [comment]
May or may not be related: https://github.com/SignalK/signalk-server-node/pull/287
